services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: finnance
    volumes:
      - db-data:/var/lib/mysql
volumes:
    db-data: