version: "2"

services:
    app:
        build: .
        command: npm start
        ports:
            - "4000:8080"
        volumes:
            - .:/usr/src/app
        depends_on:
            - mysql
        env_file:
            - .env
    mysql:
        image: mysql:8.0
        env_file:
            - .env
