version: "2"

services:
    app:
        build: .
        command: npm start
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/app
        depends_on:
            - mysql
        env_file:
            - .env
    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        env_file:
            - .env
